import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Use",
  description:
    "Film Budget Planner terms of use — your rights, our responsibilities, and how the service works.",
  alternates: {
    canonical: "/terms",
  },
  openGraph: {
    title: "Terms of Use | Film Budget Planner",
    description:
      "Film Budget Planner terms of use — your rights, our responsibilities, and how the service works.",
    url: "https://www.filmbudgetplanner.com/terms",
  },
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-bg-dark">
      {/* Nav */}
      <nav className="border-b border-white/5">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center">
          <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
            <div className="w-8 h-8 rounded-lg bg-lime flex items-center justify-center">
              <span className="text-black text-sm font-bold">F</span>
            </div>
            <span className="font-bold text-lg">Film Budget Planner</span>
          </Link>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-3xl md:text-4xl font-extrabold mb-2">Terms of Service</h1>
        <p className="text-text-muted mb-12">Last updated: April 2026</p>

        <div className="prose prose-invert max-w-none space-y-8 text-text-secondary leading-relaxed">
          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By using Film Budget Planner, you agree to these Terms of Service. If you do not agree, do not use the app.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. Description of Service</h2>
            <p>
              Film Budget Planner is a budget planning tool for film and video productions. It allows you to create,
              manage, and export production budgets.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Account Registration</h2>
            <p>
              You must create an account to use the service. You are responsible for maintaining the security of your
              account credentials.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Acceptable Use</h2>
            <p>You agree to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Provide accurate information</li>
              <li>Use the service only for lawful purposes</li>
              <li>Not attempt to access other users&apos; data</li>
              <li>Not reverse-engineer or tamper with the app</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Subscriptions and Payments</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li><strong className="text-white">Free tier:</strong> Limited features as described in the app</li>
              <li><strong className="text-white">Pro and Team tiers:</strong> Paid subscriptions managed through the Apple App Store</li>
              <li>Refunds are handled by the respective app store per their policies</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. AI-Powered Features</h2>
            <p>
              Rate estimates are generated by AI and are approximations only. They should not be relied upon as the sole
              basis for financial decisions. Actual rates vary based on many factors.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Data and Content</h2>
            <p>
              You retain ownership of all data you enter into Film Budget Planner. We do not claim ownership of your
              budgets, productions, or company information.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Limitation of Liability</h2>
            <p>Film Budget Planner is provided &quot;as is&quot; without warranty. We are not liable for:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Inaccuracies in AI-generated estimates</li>
              <li>Data loss (though we take reasonable measures to prevent it)</li>
              <li>Financial decisions made based on app data</li>
              <li>Service interruptions</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Termination</h2>
            <p>
              You may delete your account at any time. We may terminate accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">10. Changes to Terms</h2>
            <p>
              We may update these terms. Continued use of the app constitutes acceptance of updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">11. Governing Law</h2>
            <p>
              These terms are governed by the laws of the jurisdiction in which the app developer operates.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">12. Contact</h2>
            <p>
              For questions about these terms, contact us through the app or at{" "}
              <a href="mailto:support@filmbudgetplanner.com" className="text-lime hover:underline">
                support@filmbudgetplanner.com
              </a>.
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-white/5">
          <Link href="/" className="text-text-muted hover:text-white transition-colors text-sm">
            &larr; Back to home
          </Link>
        </div>
      </main>
    </div>
  );
}
